config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get '/charities', to: 'homes#index'
  get '/charities/:id', to: 'homes#index'
  get '/events', to: 'homes#index'
  get '/events/:id', to: 'homes#index'
  get '/events/new', to: 'homes#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :charities, only: [ :index, :show ]
      resources :events, only: [ :index, :show, :create ]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :website, presence: true
  validates :photo, presence: true
  validates :contact_name, presence: true
  validates :contact_role, presence: true
  validates :contact_phone, presence: true
  validates :contact_email, presence: true
  validates :mission_statement, presence: true

  has_many :events

  def address2
    "#{city}, #{state} #{zip}"
  end

end

app/models/event.rb
class Event < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true
  validates :event_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :venue, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  belongs_to :charity
  has_many :signups
  has_many :users, through: :signups
end

def formatTime
  return event.time("%Y%m%d")
end

app/models/signup.rb
class Signup < ApplicationRecord

  belongs_to :charity
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_many :signups
end

app/controllers/api/v1/charities_controller.rb
class Api::V1::CharitiesController < ApiController

  def index
    render json: Charity.all
  end

  def show
    charity = Charity.find(params[:id])
    render json: charity
  end


  # private
  # def location_params
  #   params.require(:charity).permit(:name, :address, :city, :state, :zip, :password_protected)
  # end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApiController
  def index
    render json: Event.all.sort_by { |event| event.event_date }
  end

  def show
    event = Event.find(params[:id])
    charity = Event.find(params[:id]).charity
    render json: {
      event: event,
      charity: charity
    }
  end

  def create
    charity = Charity.all
    new_event = Event.new(event_params)
    if new_event.save
      render json: {
        new_event: new_event,
        charity: charity
      }
    else
      render json: {'errors': new_event.errors.full_messages}
    end
  end


  private
  def event_params
    params.require(:event).permit(:name, :description, :event_date, :start_time, :end_time, :venue, :address, :city, :state, :zip, :venue_website, :event_page, :event_photo, :charity_id)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/homes/index.html.erb
<div id="app">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourHelp</title>
  <link href="https://fonts.googleapis.com/css?family=Playball|Special+Elite&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Vollkorn&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar grid-x">
    <div>
      <h1><a href="/" class="top-bar-logo" id="top-bar-logo">Your Help</a></h1>
    </div>
    <section>
        <div class="top-bar-charities-button">
          <%= link_to 'Charities', charities_path, class: "top-bar-button" %>
          <%= link_to 'Events', events_path, class: "top-bar-button"%>
        </div>
    </section>

    <section class="top-bar-right-section large-2 columns">
      <div class="top-bar-sign-button">
        <%- if current_user -%>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "top-bar-button" %></li>
        <%- else -%>
          <div class="top-bar-sign-button">
            <%= link_to 'Sign Up', new_user_registration_path, class: "top-bar-button" %>
            <%= link_to 'Sign In', new_user_session_path, class: "top-bar-button" %>
          </div>
        <%- end -%>
      </div>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>